# Generated by Django 4.0.5 on 2022-06-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_details_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coach',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
