# Generated by Django 4.0.5 on 2022-06-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_role_event_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
