# Generated by Django 4.0.5 on 2022-06-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_event_role_alter_event_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='role',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
