# Generated by Django 4.0.5 on 2022-06-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_recurring'),
        ('api', '0013_alter_event_role_alter_event_sport'),
    ]

    operations = [
    ]
