# Generated by Django 4.0.5 on 2022-06-15 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20220615_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offers',
            field=models.ManyToManyField(blank=True, null=True, related_name='applied_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
