# Generated by Django 4.0.5 on 2022-06-20 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_coach_organiser_user_is_coach_user_is_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked_coaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organiser',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite_coaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
