# Generated by Django 4.0.5 on 2022-06-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_event_organiser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creation_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='creation_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
