# Generated by Django 4.0.5 on 2022-06-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_event_creation_ended_event_creation_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='flexibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='reliability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
