# Generated by Django 4.0.5 on 2022-06-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_event_recurring_end_date'),
        ('api', '0022_event_voted'),
    ]

    operations = [
    ]
