# Generated by Django 4.0.5 on 2022-06-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_event_recurring_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='default_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organiser',
            name='default_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organiser',
            name='default_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organiser',
            name='default_sport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
