# Generated by Django 4.0.5 on 2022-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_organiser_default_location_organiser_default_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='qualification',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
