# Generated by Django 4.0.5 on 2022-06-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_coach_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='qualification',
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
