# Generated by Django 4.0.5 on 2022-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_organiser_default_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiser',
            name='default_location',
        ),
        migrations.RemoveField(
            model_name='organiser',
            name='default_role',
        ),
        migrations.RemoveField(
            model_name='organiser',
            name='default_sport',
        ),
        migrations.AddField(
            model_name='organiser',
            name='default_location_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organiser',
            name='default_role_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organiser',
            name='default_sport_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
