# Generated by Django 4.0.5 on 2022-06-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_organiser_default_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiser',
            name='default_location_2',
        ),
        migrations.RemoveField(
            model_name='organiser',
            name='default_role_2',
        ),
        migrations.RemoveField(
            model_name='organiser',
            name='default_sport_2',
        ),
    ]
