# Generated by Django 4.0.5 on 2022-06-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_organiser_default_location_organiser_default_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qualification',
        ),
    ]
