# Generated by Django 4.0.5 on 2022-06-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_user_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
